### PR TITLE
Enable on the fly compression for the cmssw job output (DQM)

### PR DESCRIPTION
**Pull request by dmitrijus**

### CODE REVIEW

**Comment by deguio** [comment]
@danduggan

**Comment by smorovic** [comment]
I'll merge it and make it part of the next version (1.7.3)

**Comment by deguio** [comment]
thanks @smorovic 
do you have an estimate for the next version to be made available and deployed to production?
ciao,
F.

**Comment by smorovic** [comment]
I just tested it in daq2val, so I'll make a ticket now (as usual, you can comment if you want it only in EvD BU).

**Pull request merged**
