### PR TITLE
DQM function manager changes.

### PR DESCRIPTION
**Pull request by batinkov**
Changes to the dqm logic. Now the daemon is able to determine if a run is a global run and also to figure out the type of the run: collision / cosmic / commissioning.

### CODE REVIEW

**Comment by smorovic** [comment]
Hi,

It looks ok (changellog is actually large only because of indentation). I will give it a try in VM and later merge if everything is ok.

**Comment by danduggan** [comment]
Thanks Srecko. For the propagation this time, since this was already tested
on our playback, when it's deployed to cDAQ it can also go to DQM. please
let fede/atanas know before pushing the button (or asking Lavinia to do it).

**Comment by deguio** [comment]
ciao @smorovic 
will this be part of the next version you plan to deploy?
thanks for the merge,
F.

**Comment by smorovic** [comment]
Yes, it will be in the next version. Is there a specific deadline before which you need it, or you just want it whenever we push a new version?

**Comment by deguio** [comment]
whenever you push is fine provided that it is announced at the run meeting.
let's say.. having it at a certain point next week would be nice.

thanks,
F.

**Comment by smorovic** [comment]
OK. Probably there will be a window of opportunity next week (~Thursday) during cdaq data network intervention.

**Pull request merged**
